version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80" #Caso a porta 8080 esteja em uso, altere para uma que esteja livre
    volumes:
      - .:/usr/share/nginx/html
    restart: unless-stopped